DELETE FROM soundcarrier;
DELETE FROM song;
DELETE FROM album;

DROP SEQUENCE IF EXISTS seq_articleId;

CREATE SEQUENCE seq_articleId START WITH 1000 INCREMENT BY 1;

INSERT INTO album (id, genre, label, name, release, artist) VALUES (1, 'Rock', 'Leidseplein Presse B.V.', 'The Razors Edge', '1990-01-01', 'AC/DC');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (2, 'Rock', 'Leidseplein Presse B.V.', 'Back In Black', '1980-01-01', 'AC/DC');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (3, 'Rock', 'Mercury Records Limited', 'Brothers In Arms', '1985-01-01', 'Dire Straits');
/*Generated*/
INSERT INTO album (id, genre, label, name, release, artist) VALUES (4, 'conscious hip hop', 'Soul Trax', 'Madame Butterfly', '1984-06-12', 'Cofer Brothers');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (5, 'blues', 'Basic Equipment', 'Dus` Hope', '1972-09-12', 'Dr. I-Bolit');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (6, 'ambient techno', 'BCMK', 'Love Me Crazy', '2018-02-27', 'Diskobitch');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (7, 'americana', 'Black Horizon Music', 'Lazy Afternoon', '1995-11-16', 'Seanews');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (8, 'chicago blues', 'Neoteric Music', 'Be Thankful for What Youâ€™ve Got', '2009-12-10', 'Wieland Samolak');
INSERT INTO album (id, genre, label, name, release, artist) VALUES (9, 'crust punk', 'Lampse', 'Habla el Che sobre la situaciÃ³n en el Congo', '2001-07-25', 'Fisher Hindley');


INSERT INTO song (id, title, release, album_id) VALUES (1, 'Thunderstruck', '1990-01-01', 1);
INSERT INTO song (id, title, release, album_id) VALUES (2, 'Fire Your Guns', '1990-01-01', 1);
INSERT INTO song (id, title, release, album_id) VALUES (3, 'Moneytalks', '1990-01-01', 1);
INSERT INTO song (id, title, release, album_id) VALUES (4, 'Hells Bells', '1980-01-01', 2);
INSERT INTO song (id, title, release, album_id) VALUES (5, 'Shoot to Thrill', '1980-01-01', 2);
INSERT INTO song (id, title, release, album_id) VALUES (6, 'Back In Black', '1980-01-01', 2);
INSERT INTO song (id, title, release, album_id) VALUES (7, 'Money For Nothing', '1985-01-01', 3);
INSERT INTO song (id, title, release, album_id) VALUES (8, 'Walk Of Life', '1985-01-01', 3);
INSERT INTO song (id, title, release, album_id) VALUES (9, 'Brothers In Arms', '1985-01-01', 3);
/*Generated*/
INSERT INTO song (id, title, release, album_id) VALUES (10, 'Judy con disfraz', '1993-07-08', 6);
INSERT INTO song (id, title, release, album_id) VALUES (11, 'Bulls on Parade', '2005-05-03', 7);
INSERT INTO song (id, title, release, album_id) VALUES (12, 'Knock`m Out', '2005-11-04', 8);
INSERT INTO song (id, title, release, album_id) VALUES (13, 'When I See You', '2011-05-09', 5);
INSERT INTO song (id, title, release, album_id) VALUES (14, 'Transcendental Technique', '1980-03-12', 5);
INSERT INTO song (id, title, release, album_id) VALUES (15, 'Honeysuckle', '1976-06-26', 4);
INSERT INTO song (id, title, release, album_id) VALUES (16, 'Burning in Hell', '2013-10-01', 7);
INSERT INTO song (id, title, release, album_id) VALUES (17, 'Uses of Music in Uttermost Parts', '2012-04-12', 6);
INSERT INTO song (id, title, release, album_id) VALUES (18, '6 Foot 7 Foot', '1990-08-21', 6);
INSERT INTO song (id, title, release, album_id) VALUES (19, 'Sowing Season', '1978-10-22', 7);
INSERT INTO song (id, title, release, album_id) VALUES (20, 'Propeller Seeds', '1994-10-14', 4);
INSERT INTO song (id, title, release, album_id) VALUES (21, 'Sister Kate', '1971-08-09', 5);
INSERT INTO song (id, title, release, album_id) VALUES (22, 'I hear you everywhere', '2013-09-15', 5);
INSERT INTO song (id, title, release, album_id) VALUES (23, 'InsEPto', '2018-03-19', 6);
INSERT INTO song (id, title, release, album_id) VALUES (24, 'Песня леди Джейн', '1982-06-24', 6);
INSERT INTO song (id, title, release, album_id) VALUES (25, 'Los amos del desorden', '1997-10-07', 6);
INSERT INTO song (id, title, release, album_id) VALUES (26, 'Στην υπόγα', '1984-06-12', 4);
INSERT INTO song (id, title, release, album_id) VALUES (27, 'Too Hot', '2000-12-24', 4);
INSERT INTO song (id, title, release, album_id) VALUES (28, 'When the Laughter Is Over', '1972-08-27', 8);
INSERT INTO song (id, title, release, album_id) VALUES (29, 'Trust', '2002-03-27', 5);
INSERT INTO song (id, title, release, album_id) VALUES (30, 'Kölyköd voltam', '2011-11-08', 4);
INSERT INTO song (id, title, release, album_id) VALUES (31, 'Az utolsó magyar playboy 1.', '2003-01-06', 4);
INSERT INTO song (id, title, release, album_id) VALUES (32, 'Satisfaction', '1973-03-01', 7);
INSERT INTO song (id, title, release, album_id) VALUES (33, 'L’Enterrement de Paul Fort', '1978-03-25', 4);
INSERT INTO song (id, title, release, album_id) VALUES (34, 'Now I Know', '2012-03-12', 6);
INSERT INTO song (id, title, release, album_id) VALUES (35, 'Snow', '2011-05-12', 5);
INSERT INTO song (id, title, release, album_id) VALUES (36, 'Bring Back My Happiness', '1982-09-01', 6);
INSERT INTO song (id, title, release, album_id) VALUES (37, 'Eumenides', '1998-03-05', 8);
INSERT INTO song (id, title, release, album_id) VALUES (38, 'Skeleton Swoon', '1987-01-07', 6);
INSERT INTO song (id, title, release, album_id) VALUES (39, '218 Beverly', '1994-12-24', 5);
INSERT INTO song (id, title, release, album_id) VALUES (40, 'JUMP', '2010-03-25', 8);
INSERT INTO song (id, title, release, album_id) VALUES (41, 'What the Birds Overheard', '1980-12-04', 6);
INSERT INTO song (id, title, release, album_id) VALUES (42, '(I Want to Live In) America', '1993-07-04', 6);
INSERT INTO song (id, title, release, album_id) VALUES (43, 'Twisted Streets', '1999-08-21', 5);
INSERT INTO song (id, title, release, album_id) VALUES (44, 'CHIC Ago', '1971-09-05', 5);
INSERT INTO song (id, title, release, album_id) VALUES (45, 'The Bottom Feeders', '2012-08-12', 5);
INSERT INTO song (id, title, release, album_id) VALUES (46, 'Early in the Morning', '2017-11-21', 5);
INSERT INTO song (id, title, release, album_id) VALUES (47, 'Chanson villageoise, op. 62 no. 2', '1985-06-18', 6);
INSERT INTO song (id, title, release, album_id) VALUES (48, 'Slinger’s Song', '1982-02-12', 4);
INSERT INTO song (id, title, release, album_id) VALUES (49, 'String Quartet no. 8 in C minor, op. 110: V. Largo', '2000-05-17', 5);
INSERT INTO song (id, title, release, album_id) VALUES (50, 'Precious', '1997-11-26', 4);
INSERT INTO song (id, title, release, album_id) VALUES (51, 'Episcopal Jubilate', '1973-01-25', 6);
INSERT INTO song (id, title, release, album_id) VALUES (52, 'All Master`RAP', '2017-04-03', 5);
INSERT INTO song (id, title, release, album_id) VALUES (53, 'La Nuit', '1981-05-21', 4);
INSERT INTO song (id, title, release, album_id) VALUES (54, 'Watch You Bleed', '1978-05-18', 6);
INSERT INTO song (id, title, release, album_id) VALUES (55, 'Mirage', '1985-02-09', 6);
INSERT INTO song (id, title, release, album_id) VALUES (56, 'Full Focus', '1978-01-08', 5);
INSERT INTO song (id, title, release, album_id) VALUES (57, 'Orbion', '1994-01-20', 7);
INSERT INTO song (id, title, release, album_id) VALUES (58, 'Hate That I Love You', '1988-12-15', 6);
INSERT INTO song (id, title, release, album_id) VALUES (59, 'stone cold', '2003-12-09', 4);
INSERT INTO song (id, title, release, album_id) VALUES (60, 'Born on the Fourth of July', '1970-03-20', 8);
INSERT INTO song (id, title, release, album_id) VALUES (61, 'The Becoming', '1977-03-05', 7);
INSERT INTO song (id, title, release, album_id) VALUES (62, 'Драконография', '1985-06-19', 8);
INSERT INTO song (id, title, release, album_id) VALUES (63, 'Still Wandering', '2015-06-16', 5);
INSERT INTO song (id, title, release, album_id) VALUES (64, 'I Had a Dream', '1986-07-27', 8);
INSERT INTO song (id, title, release, album_id) VALUES (65, 'My Lean Baby', '1971-09-11', 8);
INSERT INTO song (id, title, release, album_id) VALUES (66, '極楽荊姫', '1973-01-02', 8);
INSERT INTO song (id, title, release, album_id) VALUES (67, '(Die Frau hat) Rhythmus', '1976-12-17', 4);
INSERT INTO song (id, title, release, album_id) VALUES (68, 'Varjud valgusvihus', '2007-03-18', 6);
INSERT INTO song (id, title, release, album_id) VALUES (69, 'Oui mais... Non', '2003-03-21', 4);
INSERT INTO song (id, title, release, album_id) VALUES (70, 'LDN', '2000-11-26', 5);
INSERT INTO song (id, title, release, album_id) VALUES (71, 'Love Wo` Let You Down', '2016-11-25', 5);
INSERT INTO song (id, title, release, album_id) VALUES (72, 'Enjoy Yourself', '2002-05-18', 6);
INSERT INTO song (id, title, release, album_id) VALUES (73, 'Glossy World', '2012-07-04', 4);
INSERT INTO song (id, title, release, album_id) VALUES (74, 'TWO ROSES', '2015-05-27', 6);
INSERT INTO song (id, title, release, album_id) VALUES (75, 'Coast of Marseilles', '2006-03-23', 8);
INSERT INTO song (id, title, release, album_id) VALUES (76, 'Le Gant', '1998-11-25', 7);
INSERT INTO song (id, title, release, album_id) VALUES (77, 'Out in the Twilight', '2018-02-22', 4);
INSERT INTO song (id, title, release, album_id) VALUES (78, 'Uses of Music in Uttermost Parts: VIII. Island Earth', '2006-02-17', 5);
INSERT INTO song (id, title, release, album_id) VALUES (79, 'Mazā raganiņa', '1970-04-23', 7);
INSERT INTO song (id, title, release, album_id) VALUES (80, 'Shatters Within', '2000-04-19', 5);
INSERT INTO song (id, title, release, album_id) VALUES (81, 'Peter Gunn Meets Mr. Lucky', '1984-07-10', 7);
INSERT INTO song (id, title, release, album_id) VALUES (82, 'A Minor Place', '2007-09-19', 7);
INSERT INTO song (id, title, release, album_id) VALUES (83, 'Something Very Strange', '2012-02-26', 5);
INSERT INTO song (id, title, release, album_id) VALUES (84, 'Circle the Drain', '1981-02-21', 6);
INSERT INTO song (id, title, release, album_id) VALUES (85, 'Millstone', '2012-06-07', 6);
INSERT INTO song (id, title, release, album_id) VALUES (86, 'Sing a Song', '1980-06-24', 5);
INSERT INTO song (id, title, release, album_id) VALUES (87, '君+謎+私でJUMP!!', '1982-04-12', 5);
INSERT INTO song (id, title, release, album_id) VALUES (88, 'Never Meant to Know', '1970-11-23', 8);
INSERT INTO song (id, title, release, album_id) VALUES (89, 'Tình đã phai', '1986-09-28', 7);
INSERT INTO song (id, title, release, album_id) VALUES (90, 'Pong Lang Dance', '2012-07-22', 7);
INSERT INTO song (id, title, release, album_id) VALUES (91, 'Anna and Nina', '2010-02-06', 7);
INSERT INTO song (id, title, release, album_id) VALUES (92, 'How to Make a Monster', '2010-03-01', 8);
INSERT INTO song (id, title, release, album_id) VALUES (93, 'Papiroflexia', '2002-09-13', 7);
INSERT INTO song (id, title, release, album_id) VALUES (94, 'Чарльстон', '1994-03-10', 8);
INSERT INTO song (id, title, release, album_id) VALUES (95, 'Stray Bullet', '1977-02-07', 4);
INSERT INTO song (id, title, release, album_id) VALUES (96, '(I Know) I` Just the Same', '2015-11-16', 5);
INSERT INTO song (id, title, release, album_id) VALUES (97, 'Για να `εκδικηθώ', '1992-09-12', 5);
INSERT INTO song (id, title, release, album_id) VALUES (98, 'Doing the Unstuck', '2013-10-14', 7);
INSERT INTO song (id, title, release, album_id) VALUES (99, 'Exay', '2010-09-09', 4);
INSERT INTO song (id, title, release, album_id) VALUES (100, 'Spanish Caravan', '2000-09-12', 4);
INSERT INTO song (id, title, release, album_id) VALUES (101, 'Innamorato', '1986-03-07', 8);
INSERT INTO song (id, title, release, album_id) VALUES (102, 'Κά`τονε Σταύρο, κά`τονε', '1971-06-11', 7);
INSERT INTO song (id, title, release, album_id) VALUES (103, 'Πέντε Έλληνες στον Άδη', '2008-09-05', 5);
INSERT INTO song (id, title, release, album_id) VALUES (104, 'This Note’s for You', '2007-11-15', 5);



INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (1, nextval('"seq_articleid"'), 'CD', 15.99, 3, 1);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (2, nextval('"seq_articleid"'), 'CD', 13.59, 4, 2);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (3, nextval('"seq_articleid"'), 'VINYL', 5.99, 2, 3);
/*Generated*/
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (4, nextval('"seq_articleid"'), 'VINYL', 49.31, 19, 4);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (5, nextval('"seq_articleid"'), 'VINYL', 27.44, 11, 5);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (6, nextval('"seq_articleid"'), 'VINYL', 46.07, 12, 6);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (7, nextval('"seq_articleid"'), 'VINYL', 40.34, 12, 7);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (8, nextval('"seq_articleid"'), 'VINYL', 41.76, 8, 8);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (9, nextval('"seq_articleid"'), 'CD', 22.62, 5, 5);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (10, nextval('"seq_articleid"'), 'CD', 57.91, 7, 6);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (11, nextval('"seq_articleid"'), 'CD', 16.10, 1, 7);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (12, nextval('"seq_articleid"'), 'CD', 15.99, 16, 8);
INSERT INTO soundcarrier (id, articleid, medium, price, stock, album_id) VALUES (13, nextval('"seq_articleid"'), 'CD', 13.42, 13, 9);

INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('har9090', 'Hüseyin', 'Arziman', 'ADMINISTRATOR');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('lbo3144', 'Lukas', 'Boch', 'OPERATOR');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('uca1511', 'Umut Can', 'Çağlayan', 'SELLER');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('yce5586', 'Yusuf', 'Cetinkaya', 'ADMINISTRATOR');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('aci9089', 'Ali', 'Çinar', 'OPERATOR');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('auk6104', 'Abdul-Halim', 'Ukaiev', 'SELLER');
INSERT INTO clientUser (cn, firstname, lastname, role) VALUES ('zsa2157', 'Zikrihan', 'Sahin', 'ADMINISTRATOR');